version: '3.5'
services:
  calyx:
    image: studioaquatan/saffron-calyx:dev
    container_name: saffron-calyx-dev
    env_file:
      - ./calyx/src/.env.dev
    expose:
      - 8000
    depends_on:
      - bulb
    links:
      - bulb
  bulb:
    image: studioaquatan/mysql-utf8mb4:latest
    container_name: saffron-db-dev
    ports:
      - '3306:3306'
    env_file:
      - ./bulb/.env.dev
    volumes:
      - saffron-db-dev:/var/lib/mysql
  stigma:
    image: nginx:stable
    container_name: saffron-stigma-dev
    ports:
      - '8000:80'
    env_file:
      - ./calyx/src/.env.dev
    volumes:
      - ./calyx/conf/calyx.dev.conf:/etc/nginx/conf.d/default.conf
      - ./calyx/src/static:/usr/share/www/html/static
    depends_on:
      - calyx
    links:
      - calyx
  petals:
    build:
      context: ./petals
      target: develop
    image: studioaquatan/saffron-petals:dev-cache
    container_name: saffron-petals-dev
    ports:
      - '8080:3000'
    volumes:
      - ./petals/conf/petals.dev.conf:/etc/nginx/conf.d/petals.conf
      - ./petals/:/opt/petals

volumes:
  saffron-db-dev: