version: '3.5'
services:
  calyx:
    image: studioaquatan/saffron-calyx:dev
    container_name: saffron-calyx-dev
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - ./calyx/src/.env.dev
    ports:
      - "8000:8000"
    volumes:
      - ./calyx/src:/opt/calyx
    depends_on:
      - bulb
  bulb:
    image: studioaquatan/mysql-utf8mb4:latest
    container_name: saffron-db-dev
    ports:
      - '3306:3306'
    env_file:
      - ./bulb/.env.dev
    volumes:
      - saffron-db-dev:/var/lib/mysql
  petals:
    build:
      context: ./petals
      target: develop
    image: studioaquatan/saffron-petals:dev-cache
    container_name: saffron-petals-dev
    ports:
      - '8080:3000'
    volumes:
      - ./petals/conf/petals.dev.conf:/etc/nginx/conf.d/petals.conf
      - ./petals/:/opt/petals

volumes:
  saffron-db-dev: